### ISSUE TITLE
Class Diagrams and Sequence Diagrams for User Stories 

### ISSUE THREAD

**Issue by michellehardin** [Intro-to-SE-lab-Spring-22/Group-1#13]
For sprint 2 -- in Grading Excel, we need a class diagram for the proposed system and sequence diagram for each user story

**Comment by Foxman7364** [comment]
![UML class](https://user-images.githubusercontent.com/98359518/157123419-ac29fdab-4735-4081-93f2-c0ffb4863aae.jpeg)


Class Diagram for proposed system diagram

**Comment by Foxman7364** [comment]
[User Story #1.txt](https://github.com/Intro-to-SE-lab-Spring-22/Group-1/files/8201229/User.Story.1.txt)

User Story #1

**Comment by Foxman7364** [comment]
![User Story #2](https://user-images.githubusercontent.com/98359518/157136326-7ba98ee4-4d70-4423-9817-4a8217522c28.png)

User Story 2

**Comment by Foxman7364** [comment]
![User Story #3](https://user-images.githubusercontent.com/98359518/157137248-6b897ec8-95dc-4c69-aab8-a51d7e9b9841.png)

User Story 3

**Comment by Foxman7364** [comment]
![User Story #4](https://user-images.githubusercontent.com/98359518/157137605-9c4cee70-d9c2-4217-b009-45a53e7ae199.png)

User Story 4

**Comment by Foxman7364** [comment]
![User Story #5](https://user-images.githubusercontent.com/98359518/157137871-fb9a6cea-8212-4403-a836-91a2dff9537b.png)

User Story 5

**Comment by Foxman7364** [comment]
![User Story #6](https://user-images.githubusercontent.com/98359518/157138180-6f43e92d-2de2-48a4-af19-9650143cc7ba.png)

User Story 6

**Comment by Foxman7364** [comment]
![User Story #10](https://user-images.githubusercontent.com/98359518/157700940-ceacd903-bb06-4b96-9093-3b63fc11907d.png)

User Story 10

**Comment by Foxman7364** [comment]
![User Story #11](https://user-images.githubusercontent.com/98359518/157715013-7f76b65a-34c6-4a62-b4c4-4ddf9a924099.png)

User Story 11

**Comment by Foxman7364** [comment]
![User Story #11 (1)](https://user-images.githubusercontent.com/98359518/157715742-6d8189f3-d297-4d7f-b151-ffb5e271bec4.png)

User Story 11

**Comment by Foxman7364** [comment]
![User Story #12](https://user-images.githubusercontent.com/98359518/157717138-c7d9ea55-bb9d-46a0-b945-8d37acc10719.png)

User Story 12

**Comment by Foxman7364** [comment]
![User Story #13](https://user-images.githubusercontent.com/98359518/157717680-f3e5a9db-3b17-4495-b28d-7bcbbfd20132.png)

User Story 13

**Comment by Foxman7364** [comment]
Each User Story now has its own sequence diagram as well a as basic class diagram built for the entire program.

**Comment by michellehardin** [comment]
Looks good! I've posted these in a file in our main branch and tagged you for review.
